services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: example
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
        #    volumes:
        #- ollama_data:/root/.ollama

        #volumes:
        #  - ollama_data:

